name: Build and Publish

on: push

jobs:

  publish-to-docker-hub:
    if: ${{ github.ref == 'refs/heads/DART-1347-publish-to-docker-hub' || startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Build and Push Docker image
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: make docker-push

  tag-release:
    if: ${{ github.ref == 'refs/heads/DART-1347-publish-to-docker-hub' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          persist-credentials: false
      - name: Tag a release
        uses: twosixlabs-dart/dart-tag-release@v3.0.34
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          release_version: ${{ format('2.0.{0}', github.run_number) }}